import Link from "next/link";
import type { AdminOrderRecord, AdminPromotionRecord, AdminResellerRecord, AdminSupportRecord } from "@/domain/admin/types";
import type { AuditEvent } from "@/domain/reseller/types";
import type { CatalogSku } from "@/domain/catalog/types";
import { formatRetailPrice } from "@/ui/commerce/public-content";
import { PageHeading } from "@/ui/foundations/primitives";

export function AdminDashboardSurface({ orders, resellers, support, audits }: { orders: AdminOrderRecord[]; resellers: AdminResellerRecord[]; support: AdminSupportRecord[]; audits: AuditEvent[] }) {
  return <><PageHeading eyebrow="ADMIN CENTER" title="Yang perlu ditindaklanjuti" description="Ruang kerja operasional untuk menjaga katalog, pesanan, reseller, saldo, dan bantuan tetap akurat." /><div className="admin-stat-grid"><article><span>Pesanan terbuka</span><strong>{orders.filter((order) => order.fulfillmentStatus !== "fulfilled").length}</strong><Link href="/admin/orders">Tinjau pesanan</Link></article><article><span>Reseller perlu review</span><strong>{resellers.filter((reseller) => reseller.status === "pending" || reseller.status === "suspended").length}</strong><Link href="/admin/resellers">Kelola reseller</Link></article><article><span>Support prioritas</span><strong>{support.filter((ticket) => ticket.priority === "high" && ticket.status !== "resolved").length}</strong><Link href="/admin/support">Buka support</Link></article><article><span>Audit tercatat</span><strong>{audits.length}</strong><Link href="/admin/audit">Lihat audit</Link></article></div><section className="admin-panel"><header><div><p className="eyebrow">OPERASIONAL</p><h2>Jalur cepat</h2></div></header><div className="admin-quick-links"><Link href="/admin/products">Perbarui katalog</Link><Link href="/admin/pricing">Review harga</Link><Link href="/admin/balance">Rekonsiliasi saldo</Link><Link href="/admin/promotions">Kelola promosi</Link></div></section></>;
}

export function AdminProductsSurface({ products }: { products: CatalogSku[] }) {
  return <><PageHeading eyebrow="KATALOG & SKU" title="Produk" description="Kelola availability dan metadata SKU yang tampil di store." /><div className="admin-table-wrap"><table className="admin-table"><caption className="visually-hidden">Daftar produk dan SKU</caption><thead><tr><th>Produk</th><th>SKU</th><th>Retail</th><th>Stok</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{products.map((product) => <tr key={product.sku}><td>{product.productName}</td><td><code>{product.sku}</code></td><td>{formatRetailPrice(product.retailPrice)}</td><td>{product.stock}</td><td><span className={`admin-status admin-status--${product.availability}`}>{product.availability}</span></td><td><form action="/api/admin/catalog" method="post"><input type="hidden" name="sku" value={product.sku} /><input type="hidden" name="reason" value="Admin catalog review" /><input type="hidden" name="availability" value={product.availability === "available" ? "coming-soon" : "available"} /><button className="text-action" type="submit">Ubah status</button></form></td></tr>)}</tbody></table></div></>;
}

export function AdminPricingSurface({ products }: { products: CatalogSku[] }) {
  return <><PageHeading eyebrow="PRICING" title="Harga retail" description="Perubahan harga wajib disertai alasan dan dicatat ke audit." /><div className="admin-card-grid">{products.map((product) => <article className="admin-edit-card" key={product.sku}><div><h2>{product.productName}</h2><code>{product.sku}</code></div><strong>{formatRetailPrice(product.retailPrice)}</strong><form action="/api/admin/pricing" method="post"><input type="hidden" name="sku" value={product.sku} /><label>Harga baru<input name="retailPrice" type="number" min="1" defaultValue={product.retailPrice} required /></label><label>Alasan<input name="reason" required placeholder="Alasan perubahan" /></label><button className="button button--primary" type="submit">Simpan harga</button></form></article>)}</div></>;
}

export function AdminOrdersSurface({ orders }: { orders: AdminOrderRecord[] }) {
  return <><PageHeading eyebrow="ORDERS & FULFILLMENT" title="Pesanan" description="Pembayaran dan pemenuhan ditampilkan terpisah agar operasi tidak menyamakan keduanya." /><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Pembayaran</th><th>Pemenuhan</th><th>Aksi</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.id}</strong><small>{order.productName}</small></td><td>{order.customerId}</td><td>{formatRetailPrice(order.total)}</td><td>{order.paymentStatus}</td><td>{order.fulfillmentStatus}</td><td><form action="/api/admin/orders" method="post"><input type="hidden" name="id" value={order.id} /><input type="hidden" name="reason" value="Operations fulfillment review" /><select name="fulfillmentStatus" defaultValue={order.fulfillmentStatus}><option value="queued">Queued</option><option value="processing">Processing</option><option value="needs_customer_input">Needs input</option><option value="fulfilled">Fulfilled</option><option value="issue">Issue</option></select><button className="text-action" type="submit">Simpan</button></form></td></tr>)}</tbody></table></div></>;
}

export function AdminResellersSurface({ resellers }: { resellers: AdminResellerRecord[] }) {
  return <><PageHeading eyebrow="RESELLER ACCESS" title="Reseller" description="Tinjau status program dan tier tanpa membuka akses khusus di retail store." /><div className="admin-record-list">{resellers.map((reseller) => <article key={reseller.userId}><div><strong>{reseller.email}</strong><span>{reseller.userId}</span></div><span className={`admin-status admin-status--${reseller.status}`}>{reseller.status} {reseller.tier ? `· ${reseller.tier}` : ""}</span><form action="/api/admin/resellers" method="post"><input type="hidden" name="userId" value={reseller.userId} /><input type="hidden" name="reason" value="Admin reseller review" /><select name="status" defaultValue={reseller.status}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="suspended">Suspended</option></select><select name="tier" defaultValue={reseller.tier ?? "bronze"}><option value="bronze">Bronze</option><option value="silver">Silver</option><option value="gold">Gold</option></select><button className="text-action" type="submit">Simpan</button></form></article>)}</div></>;
}

export function AdminBalanceSurface({ balances }: { balances: { resellerId: string; balance: number }[] }) { return <><PageHeading eyebrow="FINANCE" title="Saldo reseller" description="Penyesuaian saldo memerlukan alasan dan audit trail." /><div className="admin-record-list">{balances.map((balance) => <article key={balance.resellerId}><div><strong>{balance.resellerId}</strong><span>Saldo tercatat</span></div><strong>{formatRetailPrice(balance.balance)}</strong><form action="/api/admin/balance" method="post"><input type="hidden" name="resellerId" value={balance.resellerId} /><label className="visually-hidden" htmlFor={`balance-${balance.resellerId}`}>Penyesuaian saldo</label><input id={`balance-${balance.resellerId}`} name="amount" type="number" step="1000" placeholder="+ / -" required /><input name="reason" placeholder="Alasan" required /><button className="text-action" type="submit">Simpan</button></form></article>)}</div></>; }

export function AdminPromotionsSurface({ promotions }: { promotions: AdminPromotionRecord[] }) { return <><PageHeading eyebrow="PROMOTIONS & CMS" title="Promosi" description="Konten promosi melalui status lifecycle yang eksplisit." /><div className="admin-record-list">{promotions.map((promotion) => <article key={promotion.id}><div><strong>{promotion.name}</strong><span>{promotion.startsAt} — {promotion.endsAt}</span></div><span className="admin-status">{promotion.status}</span><form action="/api/admin/promotions" method="post"><input type="hidden" name="id" value={promotion.id} /><input type="hidden" name="reason" value="Content calendar review" /><select name="status" defaultValue={promotion.status}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="live">Live</option><option value="ended">Ended</option></select><button className="text-action" type="submit">Simpan</button></form></article>)}</div></>; }

export function AdminSupportSurface({ tickets }: { tickets: AdminSupportRecord[] }) { return <><PageHeading eyebrow="SUPPORT OPERATIONS" title="Support queue" description="Kelola isu customer dengan konteks prioritas dan status." /><div className="admin-record-list">{tickets.map((ticket) => <article key={ticket.id}><div><strong>{ticket.subject}</strong><span>{ticket.id} · {ticket.customerId}</span></div><span className={`admin-status admin-status--${ticket.priority}`}>{ticket.priority} · {ticket.status}</span><form action="/api/admin/support" method="post"><input type="hidden" name="id" value={ticket.id} /><input type="hidden" name="reason" value="Support queue review" /><select name="status" defaultValue={ticket.status}><option value="open">Open</option><option value="pending">Pending</option><option value="resolved">Resolved</option></select><button className="text-action" type="submit">Simpan</button></form></article>)}</div></>; }

export function AdminAuditSurface({ events }: { events: AuditEvent[] }) { return <><PageHeading eyebrow="AUDIT LOG" title="Audit events" description="Jejak perubahan sensitif yang dilakukan admin, reseller, dan finance." />{events.length ? <div className="admin-record-list">{events.map((event) => <article key={event.id}><div><strong>{event.action}</strong><span>{event.actorId} → {event.targetId}</span></div><time dateTime={event.createdAt}>{event.createdAt === new Date(0).toISOString() ? "Development" : event.createdAt}</time><code>{JSON.stringify(event.details)}</code></article>)}</div> : <section className="admin-empty"><h2>Belum ada audit event</h2><p>Perubahan sensitif akan muncul setelah ada aktivitas.</p></section>}</>; }
