import { CsrfInput } from "@/ui/security/csrf-input";
import Link from "next/link";
import type { RetailCart, RetailOrder } from "@/domain/retail/types";
import type { ResellerApplication } from "@/infrastructure/reseller/reseller-application-repository";
import { formatRetailPrice } from "@/ui/commerce/public-content";
import { PageHeading, PageWidth } from "@/ui/foundations/primitives";

export function CartSurface({ cart, error = "", added = false }: { cart: RetailCart; error?: string; added?: boolean }) {
  return <main className="retail-page"><PageWidth><PageHeading eyebrow="KERANJANG RETAIL" title="Keranjang" description="Harga yang tampil adalah harga retail dan akan diperiksa kembali saat checkout." />
    {added && <p className="retail-notice" role="status">Produk ditambahkan ke keranjang.</p>}
    {error && <p className="retail-error" role="alert">{error} <Link href="/shop">Kembali ke Belanja</Link></p>}
    {cart.removedSkus.length > 0 && <p className="retail-notice" role="status">{cart.removedSkus.join(", ")} dihapus karena sudah tidak tersedia.</p>}
    {cart.lines.length === 0 ? <section className="retail-empty"><h2>Keranjang masih kosong</h2><p>Pilih produk digital untuk melihat ringkasan harga retail di sini.</p><Link className="button button--primary" href="/shop">Jelajahi produk</Link></section> : <div className="retail-cart-layout"><section className="retail-cart-lines" aria-label="Produk di keranjang">{cart.lines.map((line) => <article className="retail-cart-line" key={line.sku}><div><h2>{line.productName}</h2><p>{line.sku} · {formatRetailPrice(line.retailPrice)} / produk</p></div><form action="/api/cart/items" method="post"><CsrfInput /><input type="hidden" name="sku" value={line.sku} /><label>Jumlah <input name="quantity" type="number" min="1" max="99" defaultValue={line.quantity} /></label><button className="button button--secondary" name="intent" value="update" type="submit">Perbarui</button><button className="text-action" name="intent" value="remove" type="submit">Hapus</button></form></article>)}</section><aside className="retail-summary"><h2>Ringkasan</h2><div><span>Subtotal retail</span><strong>{formatRetailPrice(cart.subtotal)}</strong></div><small>Total diperiksa ulang dari katalog saat melanjutkan.</small><Link className="button button--primary" href="/checkout">Lanjut ke checkout</Link><Link className="retail-secondary-link" href="/shop">Tambah produk</Link></aside></div>}
  </PageWidth></main>;
}

export function SignInSurface({ returnTo, csrfToken, error = "", demoMode = false }: { returnTo: string; csrfToken: string; error?: string; demoMode?: boolean }) {
  return <main className="retail-page auth-page"><PageWidth><section className="auth-card"><p className="eyebrow">MASUK KE BACSHOP</p><h1>Pesanan dan aktivasi tersimpan di akunmu.</h1><p>Masuk diperlukan agar pembayaran, garansi, dan status aktivasi dapat ditautkan ke akun.</p>{error && <p className="retail-error" role="alert">{error}</p>}<form action="/api/auth/sign-in" method="post" className="retail-form"><input type="hidden" name="returnTo" value={returnTo} /><input type="hidden" name="csrf" value={csrfToken} /><label>Email<input name="email" type="email" autoComplete="email" required defaultValue={demoMode ? "demo@bacshop.test" : undefined} /></label><label>Kata sandi<input name="password" type="password" autoComplete="current-password" required defaultValue={demoMode ? "bacshop-demo" : undefined} /></label><button className="button button--primary" type="submit">Masuk</button></form>{demoMode && <p className="auth-hint">Akun demo development tersedia di lingkungan development.</p>}<Link href="/auth/forgot-password">Lupa kata sandi?</Link><Link href="/auth/verify">Verifikasi email</Link><Link href={`/auth/register?returnTo=${encodeURIComponent(returnTo)}`}>Belum punya akun? Daftar</Link></section></PageWidth></main>;
}

export function RegisterSurface({ returnTo, csrfToken, error = "" }: { returnTo: string; csrfToken: string; error?: string }) {
  return <main className="retail-page auth-page"><PageWidth><section className="auth-card"><p className="eyebrow">DAFTAR AKUN CUSTOMER</p><h1>Buat akun untuk menyimpan pesanan.</h1><p>Buat akun untuk menyimpan pesanan dan status aktivasi.</p>{error && <p className="retail-error" role="alert">{error}</p>}<form action="/api/auth/register" method="post" className="retail-form"><input type="hidden" name="returnTo" value={returnTo} /><input type="hidden" name="csrf" value={csrfToken} /><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Kata sandi, minimal 10 karakter<input name="password" type="password" autoComplete="new-password" minLength={10} required /></label><button className="button button--primary" type="submit">Buat akun</button></form><Link href={`/auth/sign-in?returnTo=${encodeURIComponent(returnTo)}`}>Sudah punya akun? Masuk</Link></section></PageWidth></main>;
}

export function CheckoutSurface({ cart, state = "review", error = "" }: { cart: RetailCart; state?: "review" | "reconciled"; error?: string }) {
  return <main className="retail-page"><PageWidth><PageHeading eyebrow="CHECKOUT" title="Tinjau pesanan" description="Masuk sebagai customer diperlukan untuk menyelesaikan pembelian dan menyimpan status aktivasi." /><ol className="checkout-progress" aria-label="Tahapan checkout"><li aria-current="step">1. Tinjau</li><li>2. Pembayaran</li><li>3. Aktivasi</li></ol>
    {state === "reconciled" && <p className="retail-notice" role="alert">Harga atau ketersediaan berubah. Tinjau total terbaru lalu konfirmasi kembali.</p>}
    {error && <p className="retail-error" role="alert">{error}</p>}
    {cart.lines.length === 0 ? <section className="retail-empty"><h2>Belum ada produk untuk checkout</h2><Link className="button button--primary" href="/shop">Pilih produk</Link></section> : <div className="checkout-layout"><section className="retail-cart-lines">{cart.lines.map((line) => <article className="retail-cart-line" key={line.sku}><div><h2>{line.productName}</h2><p>{line.quantity} × {formatRetailPrice(line.retailPrice)}</p></div><strong>{formatRetailPrice(line.quantity * line.retailPrice)}</strong></article>)}<section className="checkout-form-card"><h2>Data pengiriman digital</h2><p>Email penerima dipakai untuk instruksi aktivasi dan bantuan pesanan.</p><label>Email penerima<input form="checkout-form" name="recipientEmail" type="email" autoComplete="email" required /></label></section></section><aside className="retail-summary"><h2>Total retail</h2><strong className="checkout-total">{formatRetailPrice(cart.subtotal)}</strong><small>Total dihitung ulang dari harga retail katalog oleh server. Reseller pricing tidak digunakan di checkout ini.</small><form id="checkout-form" action="/api/checkout" method="post"><CsrfInput /><input type="hidden" name="clientTotal" value={cart.subtotal} /><label>Metode pembayaran<select name="paymentMethod" defaultValue="qris" required><option value="qris">QRIS</option><option value="bank_transfer">Transfer bank</option></select></label><label className="checkbox-row"><input name="termsAccepted" type="checkbox" required /> Saya menyetujui syarat pembelian dan kebijakan aktivasi.</label><button className="button button--primary" type="submit">Konfirmasi harga dan lanjutkan</button></form></aside></div>}
  </PageWidth></main>;
}

const paymentLabels = { pending: "Menunggu Pembayaran", paid: "Pembayaran Diterima", failed: "Pembayaran Gagal", expired: "Pembayaran Kedaluwarsa", refunded: "Refund" } as const;
const fulfillmentLabels = { queued: "Menunggu diproses", processing: "Diproses", needs_customer_input: "Membutuhkan data tambahan", fulfilled: "Aktif / Selesai", issue: "Bermasalah" } as const;

export function OrderTimeline({ order }: { order: RetailOrder }) {
  return <section className="order-status-panel" aria-label="Status pembayaran dan pemenuhan"><div><span>Status pembayaran</span><strong>{paymentLabels[order.paymentStatus]}</strong></div><div><span>Status aktivasi</span><strong>{fulfillmentLabels[order.fulfillmentStatus]}</strong></div><ol className="order-timeline">{order.timeline.map((event, index) => <li key={`${event.state}-${index}`}><span aria-hidden="true">{index + 1}</span><div><strong>{event.label}</strong><time dateTime={event.occurredAt}>{event.occurredAt === new Date(0).toISOString() ? "Pembaruan status" : new Date(event.occurredAt).toLocaleString("id-ID")}</time></div></li>)}</ol>{order.paymentStatus === "paid" && order.fulfillmentStatus !== "fulfilled" && <p role="status">Pembayaran sudah diterima. Aktivasi masih berjalan dan akan mengikuti estimasi produk.</p>}</section>;
}

export function AccountHomeSurface({ displayName, orderCount, activeEntitlements, resellerApplication, csrfToken }: { displayName: string; orderCount: number; activeEntitlements: number; resellerApplication?: ResellerApplication; csrfToken: string }) {
  return <main className="retail-page"><PageWidth><PageHeading eyebrow="AKUN CUSTOMER" title={`Halo, ${displayName}`} description="Kelola pesanan, aktivasi, dan bantuan retail dari satu tempat." /><div className="account-quick-stats"><article><strong>{orderCount}</strong><span>Pesanan</span><Link href="/account/orders">Lihat pesanan</Link></article><article><strong>{activeEntitlements}</strong><span>Aktivasi berjalan</span><Link href="/account/entitlements">Lihat aktivasi</Link></article><article><strong>•</strong><span>Notifikasi</span><Link href="/account/notifications">Lihat update</Link></article></div>{resellerApplication && <section className="retail-notice" role="status"><strong>Status Program Reseller: </strong>{resellerApplication.status === "pending" ? "Pengajuan sedang ditinjau." : resellerApplication.status === "approved" ? "Disetujui." : resellerApplication.status === "suspended" ? "Ditangguhkan." : "Perlu diperbarui."} <Link href="/reseller-program">Lihat program</Link></section>}<nav className="account-links" aria-label="Navigasi akun"><Link href="/account/profile">Profil</Link><Link href="/account/security">Keamanan akun</Link><Link href="/account/sessions">Sesi aktif</Link><Link href="/account/orders">Pesanan dan riwayat</Link><Link href="/account/entitlements">Produk aktif dan perpanjangan</Link><Link href="/account/notifications">Notifikasi</Link><Link href="/account/support">Bantuan customer</Link><Link href="/reseller-program">Program reseller</Link><form action="/api/auth/sign-out" method="post"><input type="hidden" name="csrf" value={csrfToken} /><button className="text-action" type="submit">Keluar</button></form></nav></PageWidth></main>;
}
